apiVersion: v1
kind: Service
metadata:
  name: person-service-example
  labels:
    name: person-service-example
spec:
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: spring-boot-example
  type: LoadBalancer